---
- name: install epel-release
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"

- name: install mysql server
  action: "{{ ansible_pkg_mgr }} name=mariadb-server state=present"

- name: install python mysql support library
  action: "{{ ansible_pkg_mgr }} name=MySQL-python state=latest"

- name: start mysql server
  action: service name=mariadb state=started enabled=true

- name: update mysql root password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: delete anonymouse user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ""
    host_all: yes
    state: absent

- name: Insert data into mytable
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: wbdb
    state: import
    target: /home/vagrant/data.sql

- name: create a new user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_user_db_name }}.*:ALL,GRANT"
    host: "%"
    state: present

- name: Update MySQL configuration
  lineinfile:
    path: /etc/mysql/my.cnf
    regexp: '^bind-address\s*='
    line: "bind-address = 192.168.111.21-30"
  notify:
    - restart mysql
