---
- name: Add MariaDB repository
  yum_repository:
    name: MariaDB
    description: MariaDB 10.5 Repository
    baseurl: http://yum.mariadb.org/10.5/centos7-amd64
    gpgcheck: yes
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    enabled: yes

- name: Install epel-release, python mysql support library, MariaDB server and client
  yum:
    name:
      - epel-release
      - MySQL-python
      - MariaDB-server
      - MariaDB-client
    state: latest

- name: Start MariaDB server
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Update mysql root password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: delete anonymouse user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ""
    host_all: yes
    state: absent

- name: Create a new user and grant privileges for database creation
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_user_db_name }}.*:ALL,GRANT"
    host: "{{ item }}"
    state: present
  with_items:
    - "192.168.111.0/24"
    - "%"

- name: Backup existing my.cnf file
  command: cp /etc/my.cnf /etc/my.bak
  args:
    creates: /etc/server.cnf.bak
  failed_when: false
- name: cp my.cnf file
  command: cp /home/vagrant/my.cnf /etc/my.cnf

- name: Restart MySQL service
  service:
    name: mariadb
    state: restarted

- name: Create a new database
  mysql_db:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    name: "{{ mysql_user_db_name }}"
    state: present

- name: Insert data
  mysql_db:
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_user_password }}"
    name: "{{ mysql_user_db_name }}"
    state: import
    target: /home/vagrant/data.sql
