---
- name: install epel-release
  action: "{{ ansible_pkg_mgr }} name=epel-release state=latest"

- name: install mysql server
  action: "{{ ansible_pkg_mgr }} name=mariadb-server state=present"

- name: install python mysql support library
  action: "{{ ansible_pkg_mgr }} name=MySQL-python state=latest"

- name: start mysql server
  action: service name=mariadb state=started enabled=true

- name: update mysql root password
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: delete anonymouse user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: ""
    host_all: yes
    state: absent

- name: create a new user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: "{{ mysql_user }}"
    password: "{{ mysql_user_password }}"
    priv: "{{ mysql_user_db_name }}.*:ALL,GRANT"
    host: "192.168.111.0/24"
    state: present

- name: Grant privileges to the user for database creation
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: myuser
    password: "{{ mysql_user_password }}"
    priv: "wbdb.*:ALL"
    host: "{{ item }}"
    state: present
  with_items:
    - "192.168.111.0/24"
    - "%"

- name: Create a new database
  mysql_db:
    login_user: myuser
    login_password: "{{ mysql_user_password }}"
    name: wbdb
    state: present

- name: Insert data into mytable
  mysql_db:
    login_user: myuser
    login_password: "{{ mysql_user_password }}"
    name: wbdb
    state: import
    target: /home/vagrant/data.sql
