---
- hosts: DB-01
  become: yes
  vars_files:
    - /home/vagrant/main.yaml
  tasks:
    - include: /home/vagrant/install.yaml
    - name: Backup existing my.cnf file
      command: mv /etc/my.cnf /etc/my.cnf.bak
      args:
        creates: /etc/my.cnf.bak
      failed_when: false
    - name: Copy my.cnf file
      copy:
        src: /home/vagrant/my.cnf
        dest: /etc/my.cnf
