---
- hosts: DB
  become: yes
  vars_files:
    - vars/main.yaml
  tasks:
    - name : mv MaiaDB.repo file
      command: mv /home/vagrant/MariaDB.repo /etc/yum.repos.d/MariaDB.repo

    - include: tasks/install.yaml

    - name: Backup existing my.cnf file
      command: mv /etc/my.cnf /etc/my.bak
      args:
        creates: /etc/server.cnf.bak
      failed_when: false
    - name: mv my.cnf file
      command: mv /home/vagrant/my.cnf /etc/my.cnf

    - name: Restart MySQL service
      service:
        name: mariadb.service
        state: restarted

    - name: Create a new database
      mysql_db:
        login_user: myuser
        login_password: "{{ mysql_user_password }}"
        name: wbdb
        state: present

    - name: Insert data into mytable
      mysql_db:
        login_user: myuser
        login_password: "{{ mysql_user_password }}"
        name: wbdb
        state: import
        target: /home/vagrant/data.sql
