---
- hosts: DB
  become: yes
  vars_files:
    - vars/main.yaml
  tasks:
    - include: tasks/install.yaml
    - name: Backup existing my.cnf file
      command: mv /etc/my.cnf /etc/my.cnf.bak
      args:
        creates: /etc/my.cnf.d/client.cnf.bak
      failed_when: false

    - name: mv my.cnf file
      command: mv /home/vagrant/client.cnf /etc/my.cnf.d/client.cnf

    - name: Backup existing mysql-clients.cnf file
      command: mv /etc/my.cnf.d/mysql-clients.cnf /etc/my.cnf.d/mysql-clients.bak
      args:
        creates: /etc/my.cnf.d/mysql-clients.cnf.bak
      failed_when: false
    - name: mv my.cnf file
      command: mv /home/vagrant/mysql-clients.cnf /etc/my.cnf.d/mysql-clients.cnf

    - name: Backup existing server.cnf file
      command: mv /etc/my.cnf.d/server.cnf /etc/my.cnf.d/server.bak
      args:
        creates: /etc/my.cnf.d/server.cnf.bak
      failed_when: false
    - name: mv my.cnf file
      command: mv /home/vagrant/server.cnf /etc/my.cnf.d/server.cnf
