---
- hosts: DB
  become: yes
  vars_files:
    - ansible/DB/vars/main.yaml
  tasks:
    - include: ansible/DB/tasks/install.yaml
    - name: Backup existing my.cnf file
      command: mv /etc/my.cnf /etc/my.cnf.bak
      args:
        creates: /etc/my.cnf.bak
      failed_when: false
    - name: mv my.cnf file
      command: mv /home/vagrant/my.cnf /etc/my.cnf
