---
- name: Install Docker on CentOS 7
  hosts:
    - web
    - WAS
  become: true
  gather_facts: no

  tasks:
    - name: Install yum-utils, device-mapper-persistent-data, lvm2 package
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable - $basearch
        baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
        gpgcheck: yes
        gpgkey: https://download.docker.com/linux/centos/gpg
        enabled: yes

    - name: Install Docker CE
      yum:
        name: docker-ce
        state: present

    # Firewall daemon이 Docker service보다 먼저 실행돼야 함
    - name: Start firewall daemon and Docker service
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - firewalld
        - docker

    # Requirements to use Docker with Ansible
    - name: Install EPEL repository, pip package
      yum:
        name:
          - epel-release
          - python-pip
        state: present

    - name: Upgrade pip
      pip:
        name: pip==20.3
        extra_args: --upgrade

    - name: Install Docker Python library
      pip:
        name: docker
        state: present
