---
- hosts:
    - web
    - WAS
    - DB
    - haproxy
  connection: local
  serial: 1
  gather_facts: no

  tasks:
    - name: Scan host key
      command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }}
      register: keyscan

    - name: Add host key to known_hosts
      lineinfile:
        dest: ~/.ssh/known_hosts
        line: "{{ item }}"
        create: yes
      with_items:
        - "{{ keyscan.stdout_lines }}"
