# update_hosts.yaml
- name: Update /etc/hosts file
  hosts: localhost
  become: yes
  gather_facts: no
  vars:
    web_end_number: 2
    was_end_number: 2

  tasks:
    - name: Add web servers to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ host_ip }} web-{{ host_number }}"
      with_sequence: "start=1 end={{ web_end_number }}"
      vars:
        host_ip: "192.168.111.{{ 10 + item|int }}"
        host_number: '{{ "%02d"|format(item|int) }}'

    - name: Add WAS servers to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ host_ip }} WAS-{{ host_number }}"
      with_sequence: "start=1 end={{ was_end_number }}"
      vars:
        host_ip: "192.168.111.{{ 20 + item|int }}"
        host_number: '{{ "%02d"|format(item|int) }}'

    - name: Add static hosts to /etc/hosts
      blockinfile:
        path: /etc/hosts
        block: |
          192.168.111.2 ansible-server
          192.168.111.31 DB-01
          192.168.111.100 haproxy-server

    # update_inventory.yaml
    - name: Generate Ansible inventory
      template:
        src: inventory_template.j2
        dest: /etc/ansible/hosts
      delegate_to: localhost
