- name: Configure HAProxy server
  hosts: haproxy
  become: true

  tasks:
    - name: Install policycoreutils-python
      yum:
        name: policycoreutils-python
        state: present

    - name: Add SELinux port for HAProxy
      seport:
        ports: 3000
        proto: tcp
        setype: http_port_t
        state: present

    - name: Install HAProxy
      yum:
        name: haproxy
        state: present

    - name: Create directory for HAProxy stats socket
      file:
        path: /run/haproxy
        state: directory
        owner: haproxy
        group: haproxy
        mode: "0660"

    - name: Copy HAProxy configuration file
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
