- name: Configure HAProxy server
  hosts: haproxy
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Install policycoreutils-python and HAProxy
      yum:
        name:
        - policycoreutils-python
        - haproxy
        state: present

    - name: Add SELinux port for HAProxy
      seport:
        ports: "{{ haproxy_port }}"
        proto: tcp
        setype: http_port_t
        state: present

    - name: Create directory for HAProxy stats socket
      file:
        path: "{{ haproxy_stats_dir }}"
        state: directory
        owner: haproxy
        group: haproxy
        mode: "0660"

    - name: Copy HAProxy configuration file
      template:
        src: "{{ haproxy_config_src }}"
        dest: "{{ haproxy_config_dest }}"
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
