---
- name: Install Nginx in Docker container
  hosts: web
  become: yes
  tasks:
    - name: Build Nginx Docker image
      docker_image:
        build:
          path: /home/vagrant/docker
          pull: no
        push: no
        name: my-nginx-image
        source: build

    - name: Run Nginx Docker container
      docker_container:
        name: my-nginx-container
        image: my-nginx-image
        state: started
        ports:
          - "80:80"
