---
- name: Install Nginx in Docker container
  hosts: web
  become: yes
  tasks:
    - name: Build Nginx Docker image
      docker_image:
        name: my-nginx-image
        source: pull

    - name: Run Nginx Docker container
      docker_container:
        name: my-nginx-container
        image: my-nginx-image
        state: started
        ports:
          - "8081:80"
