---
- name: Install Nginx in Docker container
  hosts: web
  become: yes
  tasks:
    - name: Pull Nginx image
      docker_image:
        name: ghcr.io/jaehyuk-lee/nginx-container-registry
        tag: release
        source: pull

    - name: Run Nginx container
      docker_container:
        name: my-nginx-container
        image: ghcr.io/jaehyuk-lee/nginx-container-registry:release
        state: started
        ports:
          - "80:80"
