---
- name: Install Nginx in Docker container
  hosts: web
  become: yes
  tasks:
    - name: Build Nginx Docker image
      docker_image:
        name: my-nginx-image
        source: build
        build:
          path: /home/vagrant/docker
          pull: no
        push: no

    - name: Run Nginx Docker container
      docker_container:
        name: my-nginx-container
        image: my-nginx-image
        state: started
        ports:
          - "80:80"

    - name: Start firewall daemon
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open port 80
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
