---
- name: Install Nginx in Docker container
  hosts: web
  become: yes
  vars_files:
    - vars/variables.yaml
  tasks:
    - name: Build Nginx Docker image
      docker_image:
        build:
          path: "{{ docker_build_path }}"
          pull: no
        push: no
        name: "{{ nginx_image_name }}"
        source: build

    - name: Run Nginx Docker container
      docker_container:
        name: "{{ nginx_container_name }}"
        image: "{{ nginx_image_name }}"
        state: started
        ports:
          - "{{ host_port }}:{{ container_port }}"
