---
- name: Install Nginx in Docker container
  hosts: web
  become: yes
  gather_facts: no
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Pull Nginx image
      docker_image:
        name: "{{ web_image_url }}"
        tag: "{{ web_image_tag }}"
        source: pull

    - name: Run Nginx container with WAS_IP environment variable
      docker_container:
        name: "{{ web_container_name }}"
        image: "{{ web_image_url }}:{{ web_image_tag }}"
        state: started
        ports: "{{ web_port }}"
        env:
          WAS_IP: "192.168.111.100"

    - name: Open port 80
      firewalld:
        port: "{{ item.split(':')[0] }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ web_port }}"
