---
- name: Run Tomcat Docker container
  hosts: WAS
  become: true

  tasks:
    # - name: Stop Tomcat Docker container
    #   docker_container:
    #     name: my-tomcat-container
    #     state: stopped

    # - name: Remove Tomcat Docker container
    #   docker_container:
    #     name: my-tomcat-container
    #     state: absent

    # # Docker network 파일 삭제 후 Docker 서비스 재시작 (포트 정보 캐싱 초기화)
    # - name: Stop Docker service
    #   service:
    #     name: docker
    #     state: stopped

    # - name: Remove Docker network file
    #   file:
    #     path: /var/lib/docker/network/files/local-kv.db
    #     state: absent

    # - name: Start Docker service
    #   service:
    #     name: docker
    #     state: started

    # - name: Build Docker image
    #   docker_image:
    #     build:
    #       path: /home/vagrant/docker
    #       pull: no
    #     name: my-tomcat-image
    #     source: build

    # - name: Run Tomcat Docker container
    #   docker_container:
    #     name: my-tomcat-container
    #     image: my-tomcat-image
    #     state: started
    #     ports:
    #       - "8080:8080"

    # Shell command로 Tomcat Docker 실행하기

    # - name: Check Tomcat Docker container status (shell command)
    #   shell:
    #     cmd: docker container ps | grep tomcat:9.0.87-jre11-temurin-jammy
    #   register: tomcat_container_status
    #   failed_when: tomcat_container_status.rc != 1 and tomcat_container_status.rc != 0

    # - name: Run Tomcat Docker container (shell command)
    #   shell:
    #     cmd: docker run -d -p 8080:8080 tomcat:9.0.87-jre11-temurin-jammy
    #   when: tomcat_container_status.rc != 0

    # Start firewall daemon
    - name: Start firewall daemon
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes
