---
- name: Run Nodejs Docker container
  hosts: WAS
  become: true

  tasks:
    - name: Pull Node.js image
      docker_image:
        name: ghcr.io/jaehyuk-lee/nodejs-container-registry
        tag: release
        source: pull

    - name: Run Node.js container
      docker_container:
        name: my-node-container
        image: ghcr.io/jaehyuk-lee/nodejs-container-registry:release
        state: started
        ports:
          - "3000:3000"

    # Shell command로 Tomcat Docker 실행하기

    # - name: Check Tomcat Docker container status (shell command)
    #   shell:
    #     cmd: docker container ps | grep tomcat:9.0.87-jre11-temurin-jammy
    #   register: tomcat_container_status
    #   failed_when: tomcat_container_status.rc != 1 and tomcat_container_status.rc != 0

    # - name: Run Tomcat Docker container (shell command)
    #   shell:
    #     cmd: docker run -d -p 8080:8080 tomcat:9.0.87-jre11-temurin-jammy
    #   when: tomcat_container_status.rc != 0

    # Start firewall daemon
    - name: Start firewall daemon
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open port 3000
      firewalld:
        port: 3000/tcp
        permanent: yes
        state: enabled
        immediate: yes
