---
- name: Run Nodejs Docker container
  hosts: WAS
  become: true
  gather_facts: no

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Pull Node.js image
      docker_image:
        name: "{{ was_repo }}"
        tag: "{{ was_tag }}"
        source: pull

    - name: Run Node.js container
      docker_container:
        name: "{{ was_container_name }}"
        image: "{{ was_repo }}:{{ was_tag }}"
        state: started
        ports: "{{ was_port }}"

    - name: Open WAS port
      firewalld:
        port: "{{ item.split(':')[0] }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ was_port }}"
