---
- name: Run Tomcat Docker container
  hosts: WAS
  become: true

  tasks:
    # vagrant up 처음에만 빌드하고
    # /home/vagrant/docker/webapp에 변경사항이 생겨도
    # 이후에는 빌드하지 않아서 항상 빌드하도록 셸 명령어로 변경

    # - name: Build Docker image
    #   docker_image:
    #     name: my-tomcat-image
    #     build:
    #       path: /home/vagrant/docker
    #   when: true
    #   check_mode: false

    - name: Build Docker image
      shell:
        cmd: docker build -t my-tomcat-image /home/vagrant/docker

    - name: Run Tomcat Docker container
      docker_container:
        name: my-tomcat-container
        image: my-tomcat-image
        state: started
        ports:
          - "8080:8080"

    # Shell command로 Tomcat Docker 실행하기

    # - name: Check Tomcat Docker container status (shell command)
    #   shell:
    #     cmd: docker container ps | grep tomcat:9.0.87-jre11-temurin-jammy
    #   register: tomcat_container_status
    #   failed_when: tomcat_container_status.rc != 1 and tomcat_container_status.rc != 0

    # - name: Run Tomcat Docker container (shell command)
    #   shell:
    #     cmd: docker run -d -p 8080:8080 tomcat:9.0.87-jre11-temurin-jammy
    #   when: tomcat_container_status.rc != 0

    # Start firewall daemon
    - name: Start firewall daemon
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes
