---
- name: Run Nodejs Docker container
  hosts: WAS
  become: true
  gather_facts: no

  vars_files:
    - vars/main.yaml

  tasks:
    - name: Pull WAS image
      docker_image:
        name: "{{ was_image_url }}"
        tag: "{{ was_image_tag }}"
        source: pull

    - name: Make env file
      lineinfile:
        dest: /home/vagrant/docker-env.list
        line: "{{ item }}"
        create: yes
      loop: "{{ env }}"

    - name: Run WAS container
      docker_container:
        name: "{{ was_container_name }}"
        image: "{{ was_image_url }}:{{ was_image_tag }}"
        state: started
        ports: "{{ was_port }}"
        env_file: "/home/vagrant/docker-env.list"

    - name: Open WAS port
      firewalld:
        port: "{{ item.split(':')[0] }}/tcp"
        permanent: yes
        state: enabled
        immediate: yes
      loop: "{{ was_port }}"
